---
- name: setup Mysql with db and remote login
  become: yes
  hosts: all
  gather_facts: no
  tasks:
   - name: Install mysql
     shell:
      "sudo apt install mysql-client mysql-server -y"
   - name: Install python 3
     apt:
       name: python3
       state: latest
     become: yes

   - name: Update
     apt:
       update_cache: true
       cache_valid_time: 3600
       force_apt_get: true

   - name: Install pip
     apt:
       name: python3-pip
       state: present

   - name: Install  mypysql
     pip:
       name: pymysql
       state: present
     become: yes
  
  ###############################Это работает######################
   - name: mysql-client
     become: yes
     mysql_query:
       login_unix_socket: /var/run/mysqld/mysqld.sock
       query: ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password by 'mynewpassword';
   

   ########################## ЭТО РАБОТАЕТ ########
    - name: creating mysql user (medium_post)
      mysql_user:
        login_user: root
        login_password: mynewpassword
        name: user21
        password: 24342434
        priv: '*.*:ALL'
        host: '%'
        state: present

    - name: creating medium_db
      mysql_db:
        login_user: root
        login_password: mynewpassword
        name: wp_db
        state: present

    - name: Enable remote login to mysql
      lineinfile:
         path: /etc/mysql/mysql.conf.d/mysqld.cnf
         regexp: '^bind-address'
         line: 'bind-address = 0.0.0.0'
         backup: yes
      notify:
         - Restart mysql
  handlers:
    - name: Restart mysql
      service:
        name: mysql
        state: restarted
