pipeline {
    agent any

    stages {
        stage("Deploy") {
            steps {
                sh '''
                ansible-playbook -i /home/jenkins/wp_deploy/playbook_roles.yaml | true
                echo "doneeee gesgвцфe"
                '''
            }
        }
    }
}
